In [ ]:
#BANKING ASSIGNMENT - NUMPY


In [7]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [8]:
bank_data = np.array([
    [2001,  5230.75, 720, 15,  5],
    [2002, 15890.50, 680, 22,  8],
    [2003,  2500.10, 650,  8,  2],
    [2004, 30250.00, 790, 30, 12],
    [2005,  8750.60, 710, 12,  4],
    [2006, 45000.90, 840, 40, 15],
    [2007, 11000.25, 695, 18,  6],
    [2008,  6700.00, 730, 10,  3],
    [2009, 22000.80, 765, 25, 10],
    [2010, 14500.40, 785, 28,  9]
])

In [9]:
Customer_id = bank_data [:,0]
print(Customer_id)

Account_balance=bank_data[:,1]
print(Account_balance)

creadit_score=bank_data[:,2]
print(creadit_score)

Transaction_count=bank_data[:,3]
print(Transaction_count)

Years_Active=bank_data[:,4]
print(Years_Active)

[2001. 2002. 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010.]
[ 5230.75 15890.5   2500.1  30250.    8750.6  45000.9  11000.25  6700.
 22000.8  14500.4 ]
[720. 680. 650. 790. 710. 840. 695. 730. 765. 785.]
[15. 22.  8. 30. 12. 40. 18. 10. 25. 28.]
[ 5.  8.  2. 12.  4. 15.  6.  3. 10.  9.]


In [11]:
eighth_row=bank_data[7]
print(eighth_row)

ninth_row=bank_data[8]
print(ninth_row)

tenth_row=bank_data[9]
print(tenth_row)first_row=bank_data[0]
print(first_row)

second_row=bank_data[1]
print(second_row)

third_row=bank_data[2]
print(third_row)

fourth_row=bank_data[3]
print(fourth_row)

fifth_row=bank_data[4]
print(fifth_row)

sixth_row=bank_data[5]
print(sixth_row)

seventh_row=bank_data[6]
print(seventh_row)

SyntaxError: invalid syntax (3302465187.py, line 8)

In [ ]:
Question 1: Array Creation and Manipulation

In [12]:
#Create a 4x4 identity matrix using
print(np.eye(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#Create an array of 8 zeros using
print(np.zeros(8))

[0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#Create an array of 6 ones using
print(np.ones(6))

[1. 1. 1. 1. 1. 1.]


In [15]:
#Create an array with values from 0 to 15 using
print(np.arange(0,15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
#Create an array with 8 evenly spaced values from 0 to 100 using
print(np.linspace(0,100,8))

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
Question 2: Array Attributes and Information

In [17]:
#What is the shape of the banking_data array?
print(bank_data.shape)

(10, 5)


In [18]:
#What is the data type of the banking_data array?
print(bank_data.dtype)

float64


In [19]:
#What is the size (total number of elements) of the banking_data array?
print(bank_data.size)

50


In [20]:
#What is the number of dimensions of the banking_data array?
print(bank_data.ndim)

2


In [21]:
# What is the memory size of the banking_data array in bytes?
print(bank_data.nbytes)

400


In [ ]:
Question 3: Indexing and Slicing

In [ ]:
#Extract the first row of banking_data
print(bank_data[0].astype(int))

[2001 5230  720   15    5]


In [23]:
#Extract the last row of banking_data
print(bank_data[-1].astype(int))

[ 2010 14500   785    28     9]


In [24]:
#Extract the Account_Balance column (column index 1)
print(bank_data[:,1].astype(int))

[ 5230 15890  2500 30250  8750 45000 11000  6700 22000 14500]


In [25]:
#Extract the first 4 rows and first 3 columns
print(bank_data[:4,:3].astype(int))

[[ 2001  5230   720]
 [ 2002 15890   680]
 [ 2003  2500   650]
 [ 2004 30250   790]]


In [26]:
#Extract rows 3 to 7 (inclusive)
print(bank_data[2:7].astype(int))

[[ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]]


In [ ]:
Question 4: Mathematical Operations

In [27]:
#Calculate the sum of all account balances
Sum_of_Account_balance=np.sum(bank_data[:,1])
print(Sum_of_Account_balance)

161824.3


In [28]:
#Calculate the mean account balance
mean_of_Account_balance=np.mean(bank_data[:,1])
print(mean_of_Account_balance)

16182.429999999998


In [30]:
#Calculate the standard deviation of account balances
std_of_Account_balance=np.std(bank_data[:,1])
print(std_of_Account_balance)

12427.057700059173


In [31]:
#Calculate the variance of account balances
var_of_Account_balance=np.var(bank_data[:,1])
print(var_of_Account_balance)

154431763.0806


In [32]:
#Calculate the median account balance
median_of_Account_balance=np.median(bank_data[:,1])
print(median_of_Account_balance)

12750.325


In [ ]:
Question 5: Statistical Functions


In [33]:
#Find the minimum and maximum account balances
min_max_of_Account_balance=np.min(bank_data[:,1]),np.max(bank_data[:,1])
print(min_max_of_Account_balance)

(np.float64(2500.1), np.float64(45000.9))


In [34]:
#Find the minimum and maximum credit scores
min_max_of_credit_score=np.min(bank_data[:,2]),np.max(bank_data[:,2])
print(min_max_of_Account_balance)

(np.float64(2500.1), np.float64(45000.9))


In [35]:
#calculate the percentile values for account balances (25th, 50th, 75th)
percentiles = np.percentile(bank_data[:, 1], [25, 50, 75])
print("25th percentile:", percentiles[0])
print("50th percentile (median):", percentiles[1])
print("75th percentile:", percentiles[2])

25th percentile: 7212.65
50th percentile (median): 12750.325
75th percentile: 20473.225


In [36]:
#Calculate the correlation between account balance and credit score
cor_AB_CS=np.correlate(bank_data[:,1],bank_data[:,2])
print(cor_AB_CS)

[1.24857527e+08]


In [37]:
#Calculate the covariance between account balance and credit score
cov_AB_CS=np.cov(bank_data[:,1],bank_data[:,2])
print(cov_AB_CS)

[[1.71590848e+08 6.30436644e+05]
 [6.30436644e+05 3.35027778e+03]]


In [ ]:
Question 6: Array Reshaping and Manipulation


In [38]:
#Reshape the banking_data to 5 rows × 10 columns
print(bank_data.reshape(5,10).astype(int))


[[ 2001  5230   720    15     5  2002 15890   680    22     8]
 [ 2003  2500   650     8     2  2004 30250   790    30    12]
 [ 2005  8750   710    12     4  2006 45000   840    40    15]
 [ 2007 11000   695    18     6  2008  6700   730    10     3]
 [ 2009 22000   765    25    10  2010 14500   785    28     9]]


In [39]:
#Flatten the banking_data to a 1D array
print(bank_data.flatten().astype(int))

[ 2001  5230   720    15     5  2002 15890   680    22     8  2003  2500
   650     8     2  2004 30250   790    30    12  2005  8750   710    12
     4  2006 45000   840    40    15  2007 11000   695    18     6  2008
  6700   730    10     3  2009 22000   765    25    10  2010 14500   785
    28     9]


In [40]:
#Transpose the banking_data
print(bank_data.T.astype(int))

[[ 2001  2002  2003  2004  2005  2006  2007  2008  2009  2010]
 [ 5230 15890  2500 30250  8750 45000 11000  6700 22000 14500]
 [  720   680   650   790   710   840   695   730   765   785]
 [   15    22     8    30    12    40    18    10    25    28]
 [    5     8     2    12     4    15     6     3    10     9]]


In [41]:
#Split the banking_data into 2 equal parts vertically
split_arrays = np.vsplit(bank_data, 2)
for arr in split_arrays:
    print(arr.astype(int))

[[ 2001  5230   720    15     5]
 [ 2002 15890   680    22     8]
 [ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]]
[[ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2008  6700   730    10     3]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [43]:
#Split the banking_data into 2 equal parts horizontal
h_split_arrays = np.hsplit(bank_data, 2)
for arr in h_split_arrays:
    print(arr.astype(int))

ValueError: array split does not result in an equal division

In [ ]:
Question 7: Logical Operations and Filtering


In [44]:
#Find customers with account balance greater than $100,000
Ab_greater_10000=bank_data[bank_data[:,1]>10000]
print(Ab_greater_10000.astype(int))

[[ 2002 15890   680    22     8]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [45]:
#Find customers with credit score greater than 800
CS_greater_800=bank_data[bank_data[:,2]>800]
print(CS_greater_800.astype(int))


[[ 2006 45000   840    40    15]]


In [46]:
#Find customers with transaction count greater than 50 AND credit score less than 750
TCG50_CSL750=bank_data[(bank_data[:,3]>50)&(bank_data[:,2]<750)]
print(TCG50_CSL750.astype(int))


[]


In [47]:
#Count how many customers have account balance between $10,000 and $100,000
customers_AB_G10L_L10K = bank_data[(bank_data[:, 1] >= 10000) & (bank_data[:, 1] <= 100000)]
num_customers = customers_AB_G10L_L10K.shape[0]
print(num_customers)


6


In [48]:
#Find the index of the customer with the highest credit score
customers_high_credit_score = np.max(bank_data[:,2])
print(customers_high_credit_score)
index_C_HCS = np.where(bank_data[:, 2] == customers_high_credit_score)
print(index_C_HCS)

840.0
(array([5]),)


In [ ]:
Question 8: Sorting and Searching


In [49]:
#Sort the banking_data by account balance (ascending)
sorted_bank_data = bank_data[bank_data[:, 1].argsort()]
print(sorted_bank_data.astype(int))

[[ 2003  2500   650     8     2]
 [ 2001  5230   720    15     5]
 [ 2008  6700   730    10     3]
 [ 2005  8750   710    12     4]
 [ 2007 11000   695    18     6]
 [ 2010 14500   785    28     9]
 [ 2002 15890   680    22     8]
 [ 2009 22000   765    25    10]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]]


In [50]:
#Sort the banking_data by credit score (descending)
sorted_bank_data2 = bank_data[bank_data[:, 1].argsort()[::-1]]
print(sorted_bank_data2.astype(int))


[[ 2006 45000   840    40    15]
 [ 2004 30250   790    30    12]
 [ 2009 22000   765    25    10]
 [ 2002 15890   680    22     8]
 [ 2010 14500   785    28     9]
 [ 2007 11000   695    18     6]
 [ 2005  8750   710    12     4]
 [ 2008  6700   730    10     3]
 [ 2001  5230   720    15     5]
 [ 2003  2500   650     8     2]]


In [51]:
#Find the indices that would sort the array by years active
sorted_indices = np.argsort(bank_data[:, 4])
print(sorted_indices)
sorted_by_years_active = bank_data[sorted_indices]
print(sorted_by_years_active.astype(int))

[2 7 4 0 6 1 9 8 3 5]
[[ 2003  2500   650     8     2]
 [ 2008  6700   730    10     3]
 [ 2005  8750   710    12     4]
 [ 2001  5230   720    15     5]
 [ 2007 11000   695    18     6]
 [ 2002 15890   680    22     8]
 [ 2010 14500   785    28     9]
 [ 2009 22000   765    25    10]
 [ 2004 30250   790    30    12]
 [ 2006 45000   840    40    15]]


In [52]:
#Find the customer with the second highest account balance
sorted_by_balance = bank_data[bank_data[:, 1].argsort()[::-1]]
second_highest_balance_customer = sorted_by_balance[1]
print(second_highest_balance_customer.astype(int))

[ 2004 30250   790    30    12]


In [53]:
#Find the customer with the lowest transaction count
Low_Transaction_count=np.min(bank_data[:,3])
print(Low_Transaction_count)
index_Low_Transaction_count=np.where(bank_data[:,3]==Low_Transaction_count)
print(index_Low_Transaction_count)

8.0
(array([2]),)


In [ ]:
Question 9: Mathematical Functions


In [54]:
#Calculate the absolute values of all elements
Absolute_of_BD=np.absolute(bank_data)
print(Absolute_of_BD.astype(int))


[[ 2001  5230   720    15     5]
 [ 2002 15890   680    22     8]
 [ 2003  2500   650     8     2]
 [ 2004 30250   790    30    12]
 [ 2005  8750   710    12     4]
 [ 2006 45000   840    40    15]
 [ 2007 11000   695    18     6]
 [ 2008  6700   730    10     3]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]]


In [55]:
#Calculate the square root of all account balances
Sqrt_of_Bd=np.sqrt(bank_data[:,1])
print(Sqrt_of_Bd.astype(int))


[ 72 126  50 173  93 212 104  81 148 120]


In [56]:
#Calculate the square of all credit scores
square_of_credit_scores = np.square(bank_data[:, 2])
print(square_of_credit_scores.astype(int))


[518400 462400 422500 624100 504100 705600 483025 532900 585225 616225]


In [57]:
#Calculate the exponential of all transaction counts
TC_exp_of_all=np.exp(bank_data[:,3])
print(TC_exp_of_all.astype(int))


[           3269017         3584912846               2980
     10686474581524             162754 235385266837020000
           65659969              22026        72004899337
      1446257064291]


In [58]:
#Calculate the natural logarithm of all account balances
log_of_account_balances = np.log(bank_data[:, 1])
print(log_of_account_balances)

[ 8.56230995  9.67347673  7.82408601 10.31725146  9.07687755 10.71443777
  9.30567328  8.80986281  9.9988341   9.58193151]


In [ ]:
Question 10: Advanced Operations


In [59]:
#Calculate the cumulative sum of account balances
CumulativeSum_AB=np.cumsum(bank_data[:,1])
print(CumulativeSum_AB.astype(int))


[  5230  21121  23621  53871  62621 107622 118623 125323 147323 161824]


In [61]:
#Calculate the cumulative product of transaction counts
Cumulativeproduct_AB=np.cumprod(bank_data[:,3])
print(Cumulativeproduct_AB.astype(int))


[           15           330          2640         79200        950400
      38016000     684288000    6842880000  171072000000 4790016000000]


In [62]:
#Calculate the difference between consecutive account balances
diff_Consection_AB=np.diff(bank_data[:,1])
print(diff_Consection_AB.astype(int))

[ 10659 -13390  27749 -21499  36250 -34000  -4300  15300  -7500]


In [63]:
#Calculate the gradient of account balances
gradient_AB=np.diff(bank_data[:,1])
print(gradient_AB.astype(int))

[ 10659 -13390  27749 -21499  36250 -34000  -4300  15300  -7500]


In [64]:
#Calculate the histogram of account balances with 5 bins
Histogram_AB=np.histogram(bank_data[:,1],bins=5)
print(Histogram_AB)

(array([5, 2, 1, 1, 1]), array([ 2500.1 , 11000.26, 19500.42, 28000.58, 36500.74, 45000.9 ]))


In [ ]:
Question 11: Random Numbers and Simulation


In [65]:
#Generate 6 random integers between 1 and 1000
Gen_six_integer=np.random.randint(1,100,6)
print(Gen_six_integer)

[47 48 56 93 66 96]


In [66]:
#Generate 6 random floats between 0 and 1
Gen_six_float=np.random.randint(1,100,6)
print(Gen_six_float)


[93 62 87 46 77 54]


In [67]:
#Generate 6 random numbers from normal distribution (mean=700, std=100)
random_normal = np.random.normal(loc=700, scale=100, size=6)
print(random_normal)


[588.06416529 636.80417546 588.89972383 658.95214338 672.17566374
 775.15789622]


In [68]:
#Shuffle the banking_data rows randomly
np.random.shuffle(bank_data)
print(bank_data.astype(int))

[[ 2002 15890   680    22     8]
 [ 2008  6700   730    10     3]
 [ 2005  8750   710    12     4]
 [ 2009 22000   765    25    10]
 [ 2003  2500   650     8     2]
 [ 2010 14500   785    28     9]
 [ 2007 11000   695    18     6]
 [ 2001  5230   720    15     5]
 [ 2006 45000   840    40    15]
 [ 2004 30250   790    30    12]]


In [69]:
#Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_numbers = np.random.randint(4)
print(random_numbers)

2


In [ ]:
Question 12: Linear Algebra Operations
ix

In [71]:
#Calculate the dot product of account balance and credit score columns
dot_Product_AB_CS=np.dot(Account_balance,creadit_score)
print(dot_Product_AB_CS)

124857526.75


In [ ]:
#Calculate the cross product of first two rows

In [72]:
#Calculate the norm (magnitude) of the account balance column
Norm_AB=np.linalg.norm(Account_balance)
print(Norm_AB)

64521.531583301716


In [73]:
#Create a 3x3 matrix and calculate its determinant
Matrix_3X3=np.array([[1,2,3],
 [4,5,6],
  [7,8,9]])
print(Matrix_3X3)
Matrix_3X3_determinant=np.linalg.det(Matrix_3X3)
print(Matrix_3X3_determinant)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [74]:
#Calculate the inverse of the 3x3 matrix
# Create another invertible 3x3 matrix (a different example)
invertible_matrix_2 = np.array([[3, 1, 4],
                                [1, 5, 9],
                                [2, 6, 5]])

print("Created a different invertible 3x3 matrix:")
print(invertible_matrix_2)

# Calculate the inverse of this matrix
inverse_of_matrix_2 = np.linalg.inv(invertible_matrix_2)

print("\nInverse of the second matrix:")
print(inverse_of_matrix_2.astype(int))

Created a different invertible 3x3 matrix:
[[3 1 4]
 [1 5 9]
 [2 6 5]]

Inverse of the second matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
Question 13: String Operations


In [75]:
#Convert all customer IDs to strings
Customer_id_String=Customer_id.astype(str)
print(Customer_id_String)


['2002.0' '2008.0' '2005.0' '2009.0' '2003.0' '2010.0' '2007.0' '2001.0'
 '2006.0' '2004.0']


In [76]:
#Check if any customer ID contains '100'
Customer_id_contain=Customer_id.astype(str)
print(Customer_id_contain)

['2002.0' '2008.0' '2005.0' '2009.0' '2003.0' '2010.0' '2007.0' '2001.0'
 '2006.0' '2004.0']


In [77]:
#Convert all customer IDs to uppercase (if they were strings)
customer_id_uppercase = np.char.upper(Customer_id_String)
print(customer_id_uppercase)


['2002.0' '2008.0' '2005.0' '2009.0' '2003.0' '2010.0' '2007.0' '2001.0'
 '2006.0' '2004.0']


In [78]:
#Count the length of each customer ID string
Len_of_customer_id=np.char.str_len(Customer_id_String)
print(Len_of_customer_id)

[6 6 6 6 6 6 6 6 6 6]


In [79]:
#Replace '100' with 'CUST' in customer IDs
customer_id_replaced = np.char.replace(Customer_id_String, '5', 'CUST')
#customer_id_replaced = np.char.replace(customer_id_replaced, '10', 'CUST')
print(customer_id_replaced)

['2002.0' '2008.0' '200CUST.0' '2009.0' '2003.0' '2010.0' '2007.0'
 '2001.0' '2006.0' '2004.0']


In [ ]:
Question 14: Date and Time Operations


In [80]:
#Convert years active to months
years_active_months = Years_Active * 12
print(years_active_months.astype(int))


[ 96  36  48 120  24 108  72  60 180 144]


In [81]:
#Calculate the average years active
Avg_years_active=np.mean(Years_Active)
print(Avg_years_active)


7.4


In [82]:
#Find customers who have been active for more than 5 years
Customer_Active_5Y=bank_data[Years_Active>5]
print(Customer_Active_5Y.astype(int))


[[ 2002 15890   680    22     8]
 [ 2009 22000   765    25    10]
 [ 2010 14500   785    28     9]
 [ 2007 11000   695    18     6]
 [ 2006 45000   840    40    15]
 [ 2004 30250   790    30    12]]


In [83]:
#Calculate the total time all customers have been active (in years)
Total_time_customer=np.sum(Years_Active)
print(Total_time_customer)


74.0


In [84]:
#Find the customer with the shortest time active
Sortest_Customer_active=np.min(Years_Active)
print(Sortest_Customer_active)
Sortest_Customer_active_index=bank_data[Years_Active==Sortest_Customer_active]
print(Sortest_Customer_active_index.astype(int))

2.0
[[2003 2500  650    8    2]]


In [ ]:
Question 15: Advanced Array Operations


In [85]:
#Apply a function to calculate 5% interest on all account balances
interest = Account_balance * 0.05
print(interest.astype(int))
new_account_balances = Account_balance + interest
print(new_account_balances.astype(int))


[ 794  335  437 1100  125  725  550  261 2250 1512]
[16685  7035  9188 23100  2625 15225 11550  5492 47250 31762]


In [86]:
#Use np.where to categorize customers by balance ranges
low_of_AB=np.percentile(Account_balance,25)
print(low_of_AB)

high_of_AB=np.percentile(Account_balance,75)
print(high_of_AB)
balance_categories_AB = np.where(Account_balance < low_of_AB, 'Low Balance',
                              np.where(Account_balance < high_of_AB, 'Medium Balance', 'High Balance'))
print(balance_categories_AB)

7212.65
20473.225
['Medium Balance' 'Low Balance' 'Medium Balance' 'High Balance'
 'Low Balance' 'Medium Balance' 'Medium Balance' 'Low Balance'
 'High Balance' 'High Balance']


In [87]:
#Use np.select to categorize customers by credit score ranges
low_of_CS=np.percentile(creadit_score,25)
print(low_of_CS)

high_of_CS=np.percentile(creadit_score,75)
print(high_of_CS)

conditions=[
    (creadit_score<low_of_CS),
    (creadit_score>=low_of_CS)&(creadit_score<high_of_CS),
    (creadit_score>=high_of_CS)
]

categories=['Low Credit Score','Medium Credit Score','High Credit Score']

credit_score_categories=np.select(conditions,categories,default='Unknown')
print(credit_score_categories)


698.75
780.0
['Low Credit Score' 'Medium Credit Score' 'Medium Credit Score'
 'Medium Credit Score' 'Low Credit Score' 'High Credit Score'
 'Low Credit Score' 'Medium Credit Score' 'High Credit Score'
 'High Credit Score']


In [88]:
#Use np.piecewise to apply different interest rates based on balance
low_of_AB=np.percentile(Account_balance,25)
print(low_of_AB)

high_of_Ab=np.percentile(Account_balance,75)
print(high_of_AB)

conditions=[
    (Account_balance<low_of_AB),
    (Account_balance>=low_of_AB)&(Account_balance<high_of_AB),
    (Account_balance>=high_of_AB)
]
# def calculate_low_interest(x):
#   return x * 0.03

# def calculate_medium_interest(x):
#   return x * 0.05

# def calculate_high_interest(x):
#   return x * 0.07
# functions=[
#     calculate_low_interest,
#     calculate_medium_interest,
#     calculate_high_interest
# ]

functions=[
    lambda x: x * 0.03,
    lambda x: x * 0.05,
    lambda x: x * 0.07
]

7212.65
20473.225


In [89]:
#Use np.apply_along_axis to calculate the sum of each row
# Calculate the sum of each row using np.apply_along_axis
row_sums = np.apply_along_axis(np.sum, 1, bank_data)

# Print the resulting row sums
print(row_sums)

[18602.5   9451.   11481.6  24809.8   5163.1  17332.4  13726.25  7971.75
 47901.9  33086.  ]
